### ISSUE TITLE
DoctrineObject: add a flag defining whether fields are underscore-separated or camel case

### ISSUE THREAD

**Issue by ZeinEddin** [doctrine/DoctrineModule#295]
It will be very helpful if the 'DoctrineModule\Stdlib\Hydrator\DoctrineObject' have a Flag defining whether array keys are underscore-separated (true) or camel case (false) like the one in 'Zend\Stdlib\Hydrator\ClassMethods', because for example if my field name is 'blog_post' the methods names have to be 'setBlog_post' and 'getBlog_post' which is not nice...!

**Comment by floriandammeyer** [comment]
@Ocramius I am a little confused about your statement about PSR-2 compliant method names. I just sifted through the PSR-1 and PSR-2 coding guidelines and the only statements about method names were that camelCase is supposed to be used. 

So, creating a getter method for a property which is in underscore_case like 'blog_post' (what you are allowed to do as PSR-1 states) should result in the camelCase representation of that property. Therefore the resulting getter method should be named 'getBlogPost', which is for example how PropelORM handles case conversion by default. Doctrine 2 also seems to use this conversion convention. Fetching an entity from the database which has underscore_case properties with corresponding camelCase setters using the entity manager works just fine.

As far as I can see, the method names that the DoctrineObject hydrator is generating at the moment like 'getBlog_posts' do not comply with the PSR-2 guidelines. Or am I missing something?? Why is this issue a "won't fix"?

This behavior of the DoctrineObject hydrator is really annoying, because it just defies the naming conventions one is used to nowadays.

**Comment by rvock** [comment]
+1

I also would like to have under_scored_field names and camelCasedGetters. Currently they need to be the same :(
```php
// Works:
protected $field_name;
public function getField_name() {}

protected $fieldName;
public function getFieldName() {}

// Does not work:
protected $field_name;
public function getFieldName() {}
```
