### ISSUE TITLE
Random 2.0.0 release?

### ISSUE THREAD

**Issue by MichaelGooden** [doctrine/DoctrineModule#576]
@TomHAnderson I see suddenly there is a 2.0.0 tag and accompanying release on Packagist, yet the tag targets the exact same commit as 1.2.0? :D

**Comment by TomHAnderson** [comment]
Yes, and it's marked as pre-release.  I don't follow your question.  
I created it because we need a starting point.

**Comment by MichaelGooden** [comment]
The standard practise is to use the `branch-alias` functionality.
```json
  "extra": {
    "branch-alias": {
      "dev-master": "1.1-dev",
      "dev-develop": "2.0-dev"
    }
```
Additionally, if you are making a "pre-release" type version, you need to actually specify that in the version tag, such as `2.0.0-alpha1`, `2.0.0-RC1` etc. Right now as just `2.0.0` Packagist and Composer are treating this as a fully stable complete release. The flair you can add on the Github Releases system is just a display thing for people browsing that specific page on Github.

**Comment by TomHAnderson** [comment]
Thanks Michael.  Does the branch-alias just need to be on the master branch?  It seems adding this to the 1.2.x branch isn't necessary because if you're using a tagged version, say, 1.2.0, it will pull the right version.  But if you fetch dev-master from composer it will pull master and adding branch aliases will keep dev-master pointed at 1.2.x until 2.0.x is moved to dev-master.  Have I got that strait?

**Comment by Ocramius** [comment]
It's too late for fixing it now - can't undo tags (causes issues for
consumers).

If 2.0.0 is a mistake, move on to another major version, if needed.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by TomHAnderson** [comment]
I don't consider it a mistake.  If 2.0.0 == 1.2.0 that's ok.  Adding the branch aliases if they are indeed as I outlined above will move people from dev-master = 1.2.0 who upped to dev-master = 2.0.0 back to dev-master = 1.2.x branch and work can continue on the 2.0 branch which will be aliased to dev-develop and it seems to me we'll need a 2.0.x branch to point that to.  Anyone left behind on 2.0.0 is not in trouble since they got there with dev-master.

**Comment by MichaelGooden** [comment]
Ocramius has a good point, now that 2.0.0 is released, any changes made must be backwards compatible with what was tagged as 2.0.0.

Additionally every change made will now need to be tagged on both 1.x and 2.x or some people are going to get left out.

If you really feel you need to make a ZF3 only version, then make a branch for it, but for love of sanity don’t tag any versions until you actually have a version to release.

**Comment by Ocramius** [comment]
The tag was done since 1.2.0 had a BC break in it, so it's actually an
understandable change. A bit annoying, of course :-\

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by MichaelGooden** [comment]
So what actually needs to happen is 1.2.1 needs to be released that reverts the BC break? This seems like the correct course of action if there is indeed a BC break in that version.

**Comment by Ocramius** [comment]
Correct.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by alcohol** [comment]
Just delete all the tags from Github and Packagist. And hang the person responsible.

**Comment by MichaelGooden** [comment]
Ummm what _is_ the BC break? I don't see any open issues for it.

**Comment by MichaelGooden** [comment]
1.2.0 is compatible with both ZF2 and ZF3, I just confirmed on a few of my projects.

If that was the "BC break", then what we need to do is just delete the 2.0.0 tag on both Github and Packagist. There has been a total of 1 installs of 2.0.0 per [Packagist](https://packagist.org/packages/doctrine/doctrine-module/stats#2.0.0).

**Comment by Ocramius** [comment]
ABSOLUTELY NOT. Do not delete tags ever.

**Comment by TomHAnderson** [comment]
I'll keep the 2.0.0 tag, create a 2.0.x branch to be aliased as dev-develop and alias 1.2.x branch as dev-master.

I merged a PR for CS fixes https://github.com/doctrine/DoctrineModule/pull/575 to master.  That will be part of 2.0.x   I'm not keen on merging it to 1.2.0 (because it offers no code functional changes) but I'll accept input on that decision from anyone else willing to read the PR.
