### ISSUE TITLE
Underscore naming strategy

### ISSUE THREAD

**Issue by karborator** [doctrine/DoctrineModule#591]
I'm trying to change the naming_strategy of entity properties from camelCase -> under_score ,
so what i'm doing to achieve the goal is to setup an configuration like:

'doctrine' => [
        'configuration' => [
            'orm_default' => [
                'naming_strategy' => \Doctrine\ORM\Mapping\UnderscoreNamingStrategy::class
            ],
        ],
plus a factory for this UnderscoreNamingStrategy .

Then I just execute

php ./vendor/doctrine/doctrine-module/bin/doctrine-module orm:convert-mapping --namespace="Application\\Entity\\" --force --from-database annotation ./module/Application/src/Entity/

but the class properties are still in camelCase ..

Any suggestions ?

**Comment by beatwade** [comment]
I meet the same situation ,try to change the console orm configuration, but it's not wokring too

**Comment by TomHAnderson** [comment]
You have a misunderstanding of what the UnderscoreNamingStrategy is.

This strategy is the mapping of field names to database column names.  Because the ORM can create the database and/or because the database may already use underscores instead of the infinitely easier UpperCase, this strategy will convert entity names to underscore delimited table names.   See https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php#L73

If you are still using `under_score_variables` then you are in the diminishing minority of PHP development today.  Engineered applications use `camelCase` for all class properties and the PSR standards forbid `_underscorePrefixedPropertyAndMethodNames` for private and protected class properties and methods.  

I strongly suggest you adopt a canonical naming strategy for your application based on PSR standards and best practices of today, not 15 years ago.

For instance:
* Entity Name: UserAddress
* Table Name: UserAddress

If I know the ERD (see https://www.skipper18.com) then I know the database names too.  There is not a disconnect.

**Comment by beatwade** [comment]
@TomHAnderson I know what the meaning of the PSR standards and keep try to the best practices,
but if we use doctrine for refactoring some old projects which use pure pdo prase for backend , and at the front side the fieds will be as a map of database filed name eg: user_id=>user_id
so how to handle these?
@karborator about 1 hour digging into the source code I foud this can handle the tablize filed issues in orm but not elegant ,and still can't know if doctrine has some official suggestion or not
in 
Doctrine/ORM/Mapping/Driver/DatabaseDriver.php:553
```php
    private function getFieldNameForColumn($tableName, $columnName, $fk = false)
    {
        if (isset($this->fieldNamesForColumns[$tableName]) && isset($this->fieldNamesForColumns[$tableName][$columnName])) {
            return $this->fieldNamesForColumns[$tableName][$columnName];
        }

        $columnName = strtolower($columnName);

        // Replace _id if it is a foreignkey column
        if ($fk) {
            $columnName = str_replace('_id', '', $columnName);
        }
        return Inflector::camelize($columnName);
    }
```
replace the camelize to 
```
       return Inflector::tableize($columnName);
```
will get the tablize filed name

**Comment by TomHAnderson** [comment]
If I understand your question correctly you're asking, "How do I create an ERD on top of an existing database such that the Doctrine side is normalized and the database table and fields do not change?"

That answer is it's configuration of the metadata.  I've done this with two databases larger than 120 tables each and some smaller ones.  For help with this I still recommend https://www.skipper18.com

**Comment by beatwade** [comment]
@TomHAnderson many thanks got it , this tool is very helpfull, but how about at  console command side in doctrine , it can covert mapping auto to tablelize filed name? I wanna try to use console command do it automatically ^-^

**Comment by TomHAnderson** [comment]
Please mind your diction so we can better understand one another.  Doctrine can analyze your `metadata` and create a `schema`.  If you're using the `UnderscoreNamingStrategy` then your `schema` will reflect that `strategy`.  The command line for this is `orm:schema-tool:update --dump-sql` and of course you will put that output into `migrations`.  A great use of this feature is to add `referential integrity` to an old database.  Creating an `ERD` mapped to an existing database takes me 30 table / day.

**Comment by TomHAnderson** [comment]
@karborator can you close this issue?
