### ISSUE TITLE
DoctrineObject::handleTypeConversions doesn't respect nullable types

### ISSUE THREAD

**Issue by rieschl** [doctrine/DoctrineModule#640]
When I have a field which can be nullable, e.g. a nullable `string`, the `handleTypeConversions` method casts the `null` value to an [empty `string`](https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php#L535).

Instead, it should check if the field can be `null` and if the `value` is `null` it should return `null`.

I tried it with `2.1.3`. On first glance, a fix can be somewhat complicated because the `ClassMetadata` interface doesn't have any methods to determine if the field is nullable. The ORM implementation has `isNullable` and `getFieldMapping` methods.

On the other hand, just adding
```
        if ($value === null) {
            return null;
        }
```
on top of `handleTypeConversions` doesn't break any tests, so either it's as simple as that or the current tests don't cover that scenario. Given the high code coverage of the package, maybe you should consider adding a [mutation framework](https://github.com/infection/infection) in that case ;)

PS: I just noticed that the return type annotation in the DocBlock of `handleTypeConversions` seems to be wrong.

**Comment by tupikoff** [comment]
The same problem with an integer.

**Comment by rieschl** [comment]
> The same problem with an integer.

It's probably the same issue with all types, because they are "force" casted to a certain type.

**Comment by tupikoff** [comment]
Except date

**Comment by TomHAnderson** [comment]
First off, I agree about the problem.  It was an issue long before I came to the project and it just affected me recently.  For https://github.com/API-Skeletons/zf-doctrine-graphql I created hydrator strategies for all the non-text fields e.g. https://github.com/API-Skeletons/zf-doctrine-graphql/blob/master/test/config/autoload/zf-doctrine-graphql.global.php#L151-L157

Changing the hydrator in this module would mean a new major release.  This will remain a possibility but I'd like some feedback on other solutions too before resorting to a new release.

**Comment by rieschl** [comment]
What about an additional optional constructor parameter or setter method? That wouldn't break BC.

**Comment by TomHAnderson** [comment]
I'm going to play devils non-advocate for a bit here.

Since the included hydrator works but does not work for the rules you expect (which are strict typing and a fair complaint) yet it is configurable with strategies why can't you just make it into what you want on a case by case basis?  I think a brand new strict typing hydrator would be preferred to any change to the existing one.  Thoughts on this?

**Comment by rieschl** [comment]
I'm mainly a _user_ of Doctrine and not sure if my suggestions are "Doctrine" material. I'd rather leave that to you geniuses :)

I've stumbled upon this behavior when upgrading the package from `0.x`. Of course, bc breaks can happen here, especially in pre-1.0 versions.
Nevertheless, I thought the hydrator would respect nullable types and when a field is hydrated after being processed by the `Form`s `ToNull` filter I didn't expect it to change it back to an empty string (or whatever type it is in the db). That's why I raised this issue.

Yes, I could implement my own strategies or extend the `DoctrineObject` and change it to my liking or write my own hydrator, but I think that basic stuff can (and should) be done by Doctrine itself, because the current behavior just ignores the possibility to store `NULL` in the database in many cases. That "feels" like a bug.

That said, my preferred variant is that this behavior is fixed here somehow and quickly so that I don't have to change/implement too much in every project I use this module :)
All my other projects still use a `0.x` version where nullable types are "correctly" hydrated.

If you prefer to write a new (or extended) `NullableAwareDoctrineObject` hydrator (or however you name it), that's of course fine by me :)

**Comment by TomHAnderson** [comment]
Including keeping nulls as nulls what you're asking for is completely possible with hydrator strategies.  I know this because I just created a hydrator centric GraphQL for Doctrine: https://github.com/API-Skeletons/zf-doctrine-graphql  Take a look at the unit test config to see how the hydrators are assigned: https://github.com/API-Skeletons/zf-doctrine-graphql/blob/master/test/config/autoload/zf-doctrine-graphql.global.php#L151-L157 but they are assigned on a per-entity level.  (p.s. you could use the hydrator generator for zf-doctrine-graphql in your own code)

A hydrator that can introspect the entity and correctly assign strategies for each field based on their type would be a welcome addition to this repository.  Please remember this repository is for BOTH ORM and ODM.  The best way to see change happen is to make change happen.  Any valid contribution you can make towards your goal in relation to this project would be welcome.

**Comment by diego-sorribas** [comment]
Hi @TomHAnderson ,  your solution of use strategies works ? The handleTypeConversions method is called before the strategy is applied or I am wrong?

Thanks!

**Comment by TomHAnderson** [comment]
I think you're right that handleTypeConversions is called first.  But yes, my approach of strategies does work well.  Check them out at https://github.com/API-Skeletons/zf-doctrine-graphql

http://graphql.apiskeletons.com/en/latest/hydrators.html

**Comment by TomHAnderson** [comment]
#646
